<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 * It contains the list of actions to be exectued as part of an install process.
 * Do not modify it, as it could be overwritten.
 */
$actions=array (
  0 => 
  array (
    'actionProvider' => 'redirectAction',
    'params' => 
    array (
      'packageName' => 'mouf/utils.log.errorlog_logger',
      'redirectUrl' => 'vendor/mouf/utils.log.errorlog_logger/src/install.php',
    ),
    'status' => 'todo',
    'selfEdit' => false,
  ),
);
$finalUrl=NULL;
$confirmationMessage=NULL;
?>